### ISSUE TITLE
Can I Use It For Web Based Application And if Yes How 

### ISSUE THREAD

**Issue by imtiyaz4410** [iamonuwa/Digital-Persona-SDK#1]

**Comment by iamonuwa** [comment]
Yes, I used java applet to code up mine

**Comment by imtiyaz4410** [comment]
Can You Plz Give That code

**Comment by iamonuwa** [comment]
Hi @imtiyaz4410,

I'll look for the code for you

**Comment by oghenez** [comment]
can this be used for .net and any if this is trial or free

**Comment by iamonuwa** [comment]
Hi @oghenez, 

If you have the device, this is just the sdk for it

**Comment by nwashangai** [comment]
Please I need the applet code

**Comment by chrisjnr** [comment]
Please how can We get access to that applet too. please I'm also stuck

**Comment by rovensilverio** [comment]
I dont know either sorry

On Feb 8, 2018 1:16 AM, "chrisjnr" <notifications@github.com> wrote:

Please how can We get access to that applet too. please I'm also stuck

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/iamonuwa/Digital-Persona-SDK/issues/1#issuecomment-363842101>,
or mute the thread
